pipeline:
  name: Build MERN-Stack-Example
  identifier: Build_abburisusmitha_MERN_Stack_Example_1718106372890
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: docker
                  identifier: Echo_Welcome_Message
                  spec:
                    connectorRef: dockerabburi
                    image: latest
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      cd server
                      yarn install;
                      yarn test;
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhorness
                    repo: abburinageswararao/dockerhorness
                    tags:
                      - latest
                    dockerfile: server/Dockerfile
                    context: server
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1718106349400
        repoName: abburisusmitha/MERN-Stack-Example
        build: <+input>
